# Generated by Django 4.1.1 on 2022-10-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='date',
        ),
    ]
