# Generated by Django 4.1.1 on 2022-10-24 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_forum_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='respondida',
            field=models.ManyToManyField(blank=True, default=None, related_name='respondida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Forum_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Done', 'Done'), ('Undone', 'Undone')], default='Undone', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.forum')),
            ],
        ),
    ]
