# Generated by Django 4.1.1 on 2022-11-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_forum_respondida_forum_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='body',
            field=models.TextField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(max_length=9999),
        ),
    ]
