# Generated by Django 4.1.2 on 2022-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_forum_body_alter_reply_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='professor',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
