# Generated by Django 4.1.1 on 2022-10-03 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0002_rename_discussion_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='likes',
            field=models.ManyToManyField(related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
