# Generated by Django 4.1.1 on 2022-10-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_answer'),
        ('discussion', '0003_problem_likes'),
    ]

    operations = [
    ]
